### ISSUE TITLE
自动生成contentType，在minio中报错

### ISSUE THREAD

**Issue by thinwonton** [1171736840/spring-file-storage#35]
自动生成contentType，在minio中报错。
这段代码获取不到excel文档的类型，所以报错了
`URLConnection.guessContentTypeFromName(fileInfo.getFilename())`
建议修改用apache Tika做mime猜测

**Comment by 1171736840** [comment]
这是根据文件名进行猜测的，你检查一下文件名有没有取到

**Comment by thinwonton** [comment]
已经检查过了，你可以写测试用例测试下不同类型的文件
![image](https://user-images.githubusercontent.com/6516187/188354576-f4c081b8-e5c7-40c6-adfd-8ea595f0385b.png)

`
java.lang.IllegalArgumentException: content type must not be null.

	at io.minio.BaseArgs$Builder.validateNotNull(BaseArgs.java:53)
	at io.minio.BaseArgs$Builder.validateNotEmptyString(BaseArgs.java:58)
	at io.minio.PutObjectArgs$Builder.contentType(PutObjectArgs.java:89)
	at cn.xuyanwu.spring.file.storage.platform.MinIOFileStorage.save(MinIOFileStorage.java:64)
	at cn.xuyanwu.spring.file.storage.FileStorageService.lambda$upload$0(FileStorageService.java:124)
	at cn.xuyanwu.spring.file.storage.aspect.UploadAspectChain.next(UploadAspectChain.java:34)
	at cn.xuyanwu.spring.file.storage.FileStorageService.upload(FileStorageService.java:130)
	at cn.xuyanwu.spring.file.storage.UploadPretreatment.upload(UploadPretreatment.java:241)
`

**Comment by 1171736840** [comment]
好的，我这边也试一下

**Comment by 1171736840** [comment]
我准备在获取 mime 为 null 时，默认设置为 application/octet-stream

**Comment by thinwonton** [comment]
修改用apache Tika做mime猜测。
我写了很多用例，可以满足

**Comment by 1171736840** [comment]
Tika 是通过读取文件内容进行识别的，因此会对通过 InputStream 上传文件的方式不太友好，如果确实有必要，可以手动调用 Tika 进行识别

```java
String contentType = ""; //调用Tika进行识别
fileStorageService.of(in).setContentType(contentType).upload();
```

**Comment by thinwonton** [comment]
> Tika 是通过读取文件内容进行识别的，因此会对通过 InputStream 上传文件的方式不太友好，如果确实有必要，可以手动调用 Tika 进行识别
> 
> ```java
> String contentType = ""; //调用Tika进行识别
> fileStorageService.of(in).setContentType(contentType).upload();
> ```


不是哦，Tika可以通过文件名猜mime的。
`    @Test
    public void testMime() {
        String fileName1 = "分层字典初始化.xlsx";
        String fileName2 = "数据导出模板.xls";
        String fileName3 = "touxiang.jpeg";

        Tika tika = new Tika();
        System.out.println(tika.detect(fileName1));
        System.out.println(tika.detect(fileName2));
        System.out.println(tika.detect(fileName3));
    }`

**Comment by 1171736840** [comment]
Tika 确实很优秀，让我研究一下怎么使用，准备在下个版本集成进去，对此你还有其它什么建议？

**Comment by 1171736840** [comment]
0.7.0版本中已集成
